"""
    https://leetcode.com/problems/find-the-difference/ 
    
    389. Find the Difference
    
    Given two strings s and t which consist of only lowercase letters.

    String t is generated by random shuffling string s and then add one more letter at a random position.

    Find the letter that was added in t.

    Example:

    Input:
    s = "abcd"
    t = "abcde"

    Output:
    e

    Explanation:
    'e' is the letter that was added.
    
    
"""

def find_the_difference(s, t):
    m = dict()
    for char in s:
        m[char] = m.get(char, 0) + 1

    for char in t:
        if m.get(char, 0) == 0:
            return char
        
        m[char] -= 1

if __name__ == '__main__':
    find_the_difference('abcd', 'baedc')